# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionReserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionReserva.Direccion'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionReserva.Telefono'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipoEStablecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionReserva.TipoEstablecimiento'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
